#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using System.ComponentModel;


namespace EffixReportSystem	
{
	public partial class EF_Contact_Attribute : INotifyPropertyChanged
	{
		private long _person_id;
		public virtual long Person_id
		{
		   get
		   {
		       return this._person_id;
		   }
		   set
		   {
		       if( Person_id == value )
		  return;
		 
		  _person_id = value;
		  this.OnPropertyChanged("Person_id");
		   }
		}
		private long _field_name_id;
		public virtual long Field_name_id
		{
		   get
		   {
		       return this._field_name_id;
		   }
		   set
		   {
		       if( Field_name_id == value )
		  return;
		 
		  _field_name_id = value;
		  this.OnPropertyChanged("Field_name_id");
		   }
		}
		private string _value;
		public virtual string Value
		{
		   get
		   {
		       return this._value;
		   }
		   set
		   {
		       if( Value == value )
		  return;
		 
		  _value = value;
		  this.OnPropertyChanged("Value");
		   }
		}
		private int? _list_index;
		public virtual int? List_index
		{
		   get
		   {
		       return this._list_index;
		   }
		   set
		   {
		       if( List_index == value )
		  return;
		 
		  _list_index = value;
		  this.OnPropertyChanged("List_index");
		   }
		}
		public event PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged( string info )
		{
			if( this.PropertyChanged != null)
				this.PropertyChanged( this, new PropertyChangedEventArgs( info ) );
		}
	}
}
