#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using System.ComponentModel;


namespace EffixReportSystem	
{
	public partial class EF_Contact_Field_Type : INotifyPropertyChanged
	{
		private long _field_type_id;
		public virtual long Field_type_id
		{
		   get
		   {
		       return this._field_type_id;
		   }
		   set
		   {
		       if( Field_type_id == value )
		  return;
		 
		  _field_type_id = value;
		  this.OnPropertyChanged("Field_type_id");
		   }
		}
		private string _field_type_name;
		public virtual string Field_type_name
		{
		   get
		   {
		       return this._field_type_name;
		   }
		   set
		   {
		       if( Field_type_name == value )
		  return;
		 
		  _field_type_name = value;
		  this.OnPropertyChanged("Field_type_name");
		   }
		}
		private string _value_type;
		public virtual string Value_type
		{
		   get
		   {
		       return this._value_type;
		   }
		   set
		   {
		       if( Value_type == value )
		  return;
		 
		  _value_type = value;
		  this.OnPropertyChanged("Value_type");
		   }
		}
		public event PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged( string info )
		{
			if( this.PropertyChanged != null)
				this.PropertyChanged( this, new PropertyChangedEventArgs( info ) );
		}
	}
}
