#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using System.ComponentModel;


namespace EffixReportSystem	
{
	public partial class EF_Dictionary : INotifyPropertyChanged
	{
		private long _id;
		public virtual long Id
		{
		   get
		   {
		       return this._id;
		   }
		   set
		   {
		       if( Id == value )
		  return;
		 
		  _id = value;
		  this.OnPropertyChanged("Id");
		   }
		}
		private string _name;
		public virtual string Name
		{
		   get
		   {
		       return this._name;
		   }
		   set
		   {
		       if( Name == value )
		  return;
		 
		  _name = value;
		  this.OnPropertyChanged("Name");
		   }
		}
		private string _type_Name;
		public virtual string Type_name
		{
		   get
		   {
		       return this._type_Name;
		   }
		   set
		   {
		       if( Type_name == value )
		  return;
		 
		  _type_Name = value;
		  this.OnPropertyChanged("Type_name");
		   }
		}
		private bool? _value;
		public virtual bool? Value
		{
		   get
		   {
		       return this._value;
		   }
		   set
		   {
		       if( Value == value )
		  return;
		 
		  _value = value;
		  this.OnPropertyChanged("Value");
		   }
		}
		public event PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged( string info )
		{
			if( this.PropertyChanged != null)
				this.PropertyChanged( this, new PropertyChangedEventArgs( info ) );
		}
	}
}
