#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using System.ComponentModel;
using EffixReportSystem;


namespace EffixReportSystem	
{
	public partial class EF_Department : INotifyPropertyChanged
	{
		private long _department_Id;
		public virtual long Department_id
		{
		   get
		   {
		       return this._department_Id;
		   }
		   set
		   {
		       if( Department_id == value )
		  return;
		 
		  _department_Id = value;
		  this.OnPropertyChanged("Department_id");
		   }
		}
		private long? _department_Parent_Id;
		public virtual long? Department_parent_id
		{
		   get
		   {
		       return this._department_Parent_Id;
		   }
		   set
		   {
		       if( Department_parent_id == value )
		  return;
		 
		  _department_Parent_Id = value;
		  this.OnPropertyChanged("Department_parent_id");
		   }
		}
		private string _department_Name;
		public virtual string Department_name
		{
		   get
		   {
		       return this._department_Name;
		   }
		   set
		   {
		       if( Department_name == value )
		  return;
		 
		  _department_Name = value;
		  this.OnPropertyChanged("Department_name");
		   }
		}
		private string _department_Type;
		public virtual string Department_type
		{
		   get
		   {
		       return this._department_Type;
		   }
		   set
		   {
		       if( Department_type == value )
		  return;
		 
		  _department_Type = value;
		  this.OnPropertyChanged("Department_type");
		   }
		}
		private string _department_Description;
		public virtual string Department_description
		{
		   get
		   {
		       return this._department_Description;
		   }
		   set
		   {
		       if( Department_description == value )
		  return;
		 
		  _department_Description = value;
		  this.OnPropertyChanged("Department_description");
		   }
		}
		private long? _department_Project_Id;
		public virtual long? Department_project_id
		{
		   get
		   {
		       return this._department_Project_Id;
		   }
		   set
		   {
		       if( Department_project_id == value )
		  return;
		 
		  _department_Project_Id = value;
		  this.OnPropertyChanged("Department_project_id");
		   }
		}
		private IList<EF_Publication> _eF_Publications = new List<EF_Publication>();
		public virtual IList<EF_Publication> EF_Publications
		{
		   get
		   {
		       return this._eF_Publications;
		   }
		}
		public event PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged( string info )
		{
			if( this.PropertyChanged != null)
				this.PropertyChanged( this, new PropertyChangedEventArgs( info ) );
		}
	}
}
