#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using System.ComponentModel;
using EffixReportSystem;


namespace EffixReportSystem	
{
	public partial class EF_Edition : INotifyPropertyChanged
	{
		private int _iD;
		public virtual int ID
		{
		   get
		   {
		       return this._iD;
		   }
		   set
		   {
		       if( ID == value )
		  return;
		 
		  _iD = value;
		  this.OnPropertyChanged("ID");
		   }
		}
		private string _edition_name;
		public virtual string Edition_name
		{
		   get
		   {
		       return this._edition_name;
		   }
		   set
		   {
		       if( Edition_name == value )
		  return;
		 
		  _edition_name = value;
		  this.OnPropertyChanged("Edition_name");
		   }
		}
		private string _edition_value;
		public virtual string Edition_value
		{
		   get
		   {
		       return this._edition_value;
		   }
		   set
		   {
		       if( Edition_value == value )
		  return;
		 
		  _edition_value = value;
		  this.OnPropertyChanged("Edition_value");
		   }
		}
		private IList<EF_SMI> _eF_SMIs = new List<EF_SMI>();
		public virtual IList<EF_SMI> EF_SMIs
		{
		   get
		   {
		       return this._eF_SMIs;
		   }
		}
		public event PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged( string info )
		{
			if( this.PropertyChanged != null)
				this.PropertyChanged( this, new PropertyChangedEventArgs( info ) );
		}
	}
}
