#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using System.ComponentModel;


namespace EffixReportSystem	
{
	public partial class EF_Field_Name : INotifyPropertyChanged
	{
		private long _field_name_id;
		public virtual long Field_name_id
		{
		   get
		   {
		       return this._field_name_id;
		   }
		   set
		   {
		       if( Field_name_id == value )
		  return;
		 
		  _field_name_id = value;
		  this.OnPropertyChanged("Field_name_id");
		   }
		}
		private long _field_type_id;
		public virtual long Field_type_id
		{
		   get
		   {
		       return this._field_type_id;
		   }
		   set
		   {
		       if( Field_type_id == value )
		  return;
		 
		  _field_type_id = value;
		  this.OnPropertyChanged("Field_type_id");
		   }
		}
		private string _name;
		public virtual string Name
		{
		   get
		   {
		       return this._name;
		   }
		   set
		   {
		       if( Name == value )
		  return;
		 
		  _name = value;
		  this.OnPropertyChanged("Name");
		   }
		}
		public event PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged( string info )
		{
			if( this.PropertyChanged != null)
				this.PropertyChanged( this, new PropertyChangedEventArgs( info ) );
		}
	}
}
