#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using System.ComponentModel;
using EffixReportSystem;


namespace EffixReportSystem	
{
	public partial class EF_MassMedia : INotifyPropertyChanged
	{
		private long _mass_media_type_id;
		public virtual long Mass_media_type_id
		{
		   get
		   {
		       return this._mass_media_type_id;
		   }
		   set
		   {
		       if( Mass_media_type_id == value )
		  return;
		 
		  _mass_media_type_id = value;
		  this.OnPropertyChanged("Mass_media_type_id");
		   }
		}
		private long? _parent_type_id;
		public virtual long? Parent_type_id
		{
		   get
		   {
		       return this._parent_type_id;
		   }
		   set
		   {
		       if( Parent_type_id == value )
		  return;
		 
		  _parent_type_id = value;
		  this.OnPropertyChanged("Parent_type_id");
		   }
		}
		private string _mass_media_type_name;
		public virtual string Mass_media_type_name
		{
		   get
		   {
		       return this._mass_media_type_name;
		   }
		   set
		   {
		       if( Mass_media_type_name == value )
		  return;
		 
		  _mass_media_type_name = value;
		  this.OnPropertyChanged("Mass_media_type_name");
		   }
		}
		private string _mass_media_type_descr;
		public virtual string Mass_media_type_descr
		{
		   get
		   {
		       return this._mass_media_type_descr;
		   }
		   set
		   {
		       if( Mass_media_type_descr == value )
		  return;
		 
		  _mass_media_type_descr = value;
		  this.OnPropertyChanged("Mass_media_type_descr");
		   }
		}
		private IList<EF_SMI> _eF_SMIs = new List<EF_SMI>();
		public virtual IList<EF_SMI> EF_SMIs
		{
		   get
		   {
		       return this._eF_SMIs;
		   }
		}
		public event PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged( string info )
		{
			if( this.PropertyChanged != null)
				this.PropertyChanged( this, new PropertyChangedEventArgs( info ) );
		}
	}
}
