#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using System.ComponentModel;
using EffixReportSystem;


namespace EffixReportSystem	
{
	public partial class EF_Publication : INotifyPropertyChanged
	{
		private long _publication_id;
		public virtual long Publication_id
		{
		   get
		   {
		       return this._publication_id;
		   }
		   set
		   {
		       if( Publication_id == value )
		  return;
		 
		  _publication_id = value;
		  this.OnPropertyChanged("Publication_id");
		   }
		}
		private long? _tonality_id;
		public virtual long? Tonality_id
		{
		   get
		   {
		       return this._tonality_id;
		   }
		   set
		   {
		       if( Tonality_id == value )
		  return;
		 
		  _tonality_id = value;
		  this.OnPropertyChanged("Tonality_id");
		   }
		}
		private string _publication_name;
		public virtual string Publication_name
		{
		   get
		   {
		       return this._publication_name;
		   }
		   set
		   {
		       if( Publication_name == value )
		  return;
		 
		  _publication_name = value;
		  this.OnPropertyChanged("Publication_name");
		   }
		}
		private long? _smi_id;
		public virtual long? Smi_id
		{
		   get
		   {
		       return this._smi_id;
		   }
		   set
		   {
		       if( Smi_id == value )
		  return;
		 
		  _smi_id = value;
		  this.OnPropertyChanged("Smi_id");
		   }
		}
		private int? _has_photo;
		public virtual int? Has_photo
		{
		   get
		   {
		       return this._has_photo;
		   }
		   set
		   {
		       if( Has_photo == value )
		  return;
		 
		  _has_photo = value;
		  this.OnPropertyChanged("Has_photo");
		   }
		}
		private long? _exclusivity_id;
		public virtual long? Exclusivity_id
		{
		   get
		   {
		       return this._exclusivity_id;
		   }
		   set
		   {
		       if( Exclusivity_id == value )
		  return;
		 
		  _exclusivity_id = value;
		  this.OnPropertyChanged("Exclusivity_id");
		   }
		}
		private long? _project_id;
		public virtual long? Project_id
		{
		   get
		   {
		       return this._project_id;
		   }
		   set
		   {
		       if( Project_id == value )
		  return;
		 
		  _project_id = value;
		  this.OnPropertyChanged("Project_id");
		   }
		}
		private DateTime? _ceation_date;
		public virtual DateTime? Ceation_date
		{
		   get
		   {
		       return this._ceation_date;
		   }
		   set
		   {
		       if( Ceation_date == value )
		  return;
		 
		  _ceation_date = value;
		  this.OnPropertyChanged("Ceation_date");
		   }
		}
		private DateTime? _publication_date;
		public virtual DateTime? Publication_date
		{
		   get
		   {
		       return this._publication_date;
		   }
		   set
		   {
		       if( Publication_date == value )
		  return;
		 
		  _publication_date = value;
		  this.OnPropertyChanged("Publication_date");
		   }
		}
		private int? _is_initiated;
		public virtual int? Is_initiated
		{
		   get
		   {
		       return this._is_initiated;
		   }
		   set
		   {
		       if( Is_initiated == value )
		  return;
		 
		  _is_initiated = value;
		  this.OnPropertyChanged("Is_initiated");
		   }
		}
		private int? _is_planed;
		public virtual int? Is_planed
		{
		   get
		   {
		       return this._is_planed;
		   }
		   set
		   {
		       if( Is_planed == value )
		  return;
		 
		  _is_planed = value;
		  this.OnPropertyChanged("Is_planed");
		   }
		}
		private string _screenshot_path;
		public virtual string Screenshot_path
		{
		   get
		   {
		       return this._screenshot_path;
		   }
		   set
		   {
		       if( Screenshot_path == value )
		  return;
		 
		  _screenshot_path = value;
		  this.OnPropertyChanged("Screenshot_path");
		   }
		}
		private long? _priority_id;
		public virtual long? Priority_id
		{
		   get
		   {
		       return this._priority_id;
		   }
		   set
		   {
		       if( Priority_id == value )
		  return;
		 
		  _priority_id = value;
		  this.OnPropertyChanged("Priority_id");
		   }
		}
		private string _url_path;
		public virtual string Url_path
		{
		   get
		   {
		       return this._url_path;
		   }
		   set
		   {
		       if( Url_path == value )
		  return;
		 
		  _url_path = value;
		  this.OnPropertyChanged("Url_path");
		   }
		}
		private long? _user_id;
		public virtual long? User_id
		{
		   get
		   {
		       return this._user_id;
		   }
		   set
		   {
		       if( User_id == value )
		  return;
		 
		  _user_id = value;
		  this.OnPropertyChanged("User_id");
		   }
		}
		private string _blob_path;
		public virtual string Blob_path
		{
		   get
		   {
		       return this._blob_path;
		   }
		   set
		   {
		       if( Blob_path == value )
		  return;
		 
		  _blob_path = value;
		  this.OnPropertyChanged("Blob_path");
		   }
		}
		private int? _image_count;
		public virtual int? Image_count
		{
		   get
		   {
		       return this._image_count;
		   }
		   set
		   {
		       if( Image_count == value )
		  return;
		 
		  _image_count = value;
		  this.OnPropertyChanged("Image_count");
		   }
		}
		private string _p_year;
		public virtual string P_year
		{
		   get
		   {
		       return this._p_year;
		   }
		   set
		   {
		       if( P_year == value )
		  return;
		 
		  _p_year = value;
		  this.OnPropertyChanged("P_year");
		   }
		}
		private string _p_month;
		public virtual string P_month
		{
		   get
		   {
		       return this._p_month;
		   }
		   set
		   {
		       if( P_month == value )
		  return;
		 
		  _p_month = value;
		  this.OnPropertyChanged("P_month");
		   }
		}
		private string _p_day;
		public virtual string P_day
		{
		   get
		   {
		       return this._p_day;
		   }
		   set
		   {
		       if( P_day == value )
		  return;
		 
		  _p_day = value;
		  this.OnPropertyChanged("P_day");
		   }
		}
		private string _project_name;
		public virtual string Project_name
		{
		   get
		   {
		       return this._project_name;
		   }
		   set
		   {
		       if( Project_name == value )
		  return;
		 
		  _project_name = value;
		  this.OnPropertyChanged("Project_name");
		   }
		}
		private long? _department_id;
		public virtual long? Department_id
		{
		   get
		   {
		       return this._department_id;
		   }
		   set
		   {
		       if( Department_id == value )
		  return;
		 
		  _department_id = value;
		  this.OnPropertyChanged("Department_id");
		   }
		}
		private EF_SMI _eF_SMI;
		public virtual EF_SMI EF_SMI
		{
		   get
		   {
		       return this._eF_SMI;
		   }
		   set
		   {
		       if( EF_SMI == value )
		  return;
		 
		  _eF_SMI = value;
		  this.OnPropertyChanged("EF_SMI");
		   }
		}
		private EF_Exclusivity _eF_Exclusivity;
		public virtual EF_Exclusivity EF_Exclusivity
		{
		   get
		   {
		       return this._eF_Exclusivity;
		   }
		   set
		   {
		       if( EF_Exclusivity == value )
		  return;
		 
		  _eF_Exclusivity = value;
		  this.OnPropertyChanged("EF_Exclusivity");
		   }
		}
		private EF_Initiated _eF_Initiated;
		public virtual EF_Initiated EF_Initiated
		{
		   get
		   {
		       return this._eF_Initiated;
		   }
		   set
		   {
		       if( EF_Initiated == value )
		  return;
		 
		  _eF_Initiated = value;
		  this.OnPropertyChanged("EF_Initiated");
		   }
		}
		private EF_Planed _eF_Planed;
		public virtual EF_Planed EF_Planed
		{
		   get
		   {
		       return this._eF_Planed;
		   }
		   set
		   {
		       if( EF_Planed == value )
		  return;
		 
		  _eF_Planed = value;
		  this.OnPropertyChanged("EF_Planed");
		   }
		}
		private EF_Photo _eF_Photo;
		public virtual EF_Photo EF_Photo
		{
		   get
		   {
		       return this._eF_Photo;
		   }
		   set
		   {
		       if( EF_Photo == value )
		  return;
		 
		  _eF_Photo = value;
		  this.OnPropertyChanged("EF_Photo");
		   }
		}
		private EF_Project _eF_Project;
		public virtual EF_Project EF_Project
		{
		   get
		   {
		       return this._eF_Project;
		   }
		   set
		   {
		       if( EF_Project == value )
		  return;
		 
		  _eF_Project = value;
		  this.OnPropertyChanged("EF_Project");
		   }
		}
		private EF_SMI_priority _eF_SMI_priority;
		public virtual EF_SMI_priority EF_SMI_priority
		{
		   get
		   {
		       return this._eF_SMI_priority;
		   }
		   set
		   {
		       if( EF_SMI_priority == value )
		  return;
		 
		  _eF_SMI_priority = value;
		  this.OnPropertyChanged("EF_SMI_priority");
		   }
		}
		private EF_Tonality _eF_Tonality;
		public virtual EF_Tonality EF_Tonality
		{
		   get
		   {
		       return this._eF_Tonality;
		   }
		   set
		   {
		       if( EF_Tonality == value )
		  return;
		 
		  _eF_Tonality = value;
		  this.OnPropertyChanged("EF_Tonality");
		   }
		}
		private EF_Department _eF_Department;
		public virtual EF_Department EF_Department
		{
		   get
		   {
		       return this._eF_Department;
		   }
		   set
		   {
		       if( EF_Department == value )
		  return;
		 
		  _eF_Department = value;
		  this.OnPropertyChanged("EF_Department");
		   }
		}
		public event PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged( string info )
		{
			if( this.PropertyChanged != null)
				this.PropertyChanged( this, new PropertyChangedEventArgs( info ) );
		}
	}
}
