#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using System.ComponentModel;


namespace EffixReportSystem	
{
	public partial class EF_SMI_Type : INotifyPropertyChanged
	{
		private long _smi_Type_Id;
		public virtual long Smi_type_id
		{
		   get
		   {
		       return this._smi_Type_Id;
		   }
		   set
		   {
		       if( Smi_type_id == value )
		  return;
		 
		  _smi_Type_Id = value;
		  this.OnPropertyChanged("Smi_type_id");
		   }
		}
		private string _smi_Type_Name;
		public virtual string Smi_type_name
		{
		   get
		   {
		       return this._smi_Type_Name;
		   }
		   set
		   {
		       if( Smi_type_name == value )
		  return;
		 
		  _smi_Type_Name = value;
		  this.OnPropertyChanged("Smi_type_name");
		   }
		}
		private string _smi_Type_Descr;
		public virtual string Smi_type_descr
		{
		   get
		   {
		       return this._smi_Type_Descr;
		   }
		   set
		   {
		       if( Smi_type_descr == value )
		  return;
		 
		  _smi_Type_Descr = value;
		  this.OnPropertyChanged("Smi_type_descr");
		   }
		}
		public event PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged( string info )
		{
			if( this.PropertyChanged != null)
				this.PropertyChanged( this, new PropertyChangedEventArgs( info ) );
		}
	}
}
