#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using System.ComponentModel;


namespace EffixReportSystem	
{
	public partial class EF_SMI : INotifyPropertyChanged
	{
		private long _smi_Id;
		public virtual long Smi_id
		{
		   get
		   {
		       return this._smi_Id;
		   }
		   set
		   {
		       if( Smi_id == value )
		  return;
		 
		  _smi_Id = value;
		  this.OnPropertyChanged("Smi_id");
		   }
		}
		private string _smi_Name;
		public virtual string Smi_name
		{
		   get
		   {
		       return this._smi_Name;
		   }
		   set
		   {
		       if( Smi_name == value )
		  return;
		 
		  _smi_Name = value;
		  this.OnPropertyChanged("Smi_name");
		   }
		}
		private long? _smi_Type_Id;
		public virtual long? Smi_type_id
		{
		   get
		   {
		       return this._smi_Type_Id;
		   }
		   set
		   {
		       if( Smi_type_id == value )
		  return;
		 
		  _smi_Type_Id = value;
		  this.OnPropertyChanged("Smi_type_id");
		   }
		}
		private string _smi_Descr;
		public virtual string Smi_descr
		{
		   get
		   {
		       return this._smi_Descr;
		   }
		   set
		   {
		       if( Smi_descr == value )
		  return;
		 
		  _smi_Descr = value;
		  this.OnPropertyChanged("Smi_descr");
		   }
		}
		private string _smi_Edition;
		public virtual string Smi_edition
		{
		   get
		   {
		       return this._smi_Edition;
		   }
		   set
		   {
		       if( Smi_edition == value )
		  return;
		 
		  _smi_Edition = value;
		  this.OnPropertyChanged("Smi_edition");
		   }
		}
		private string _smi_Edition_Descr;
		public virtual string Smi_edition_descr
		{
		   get
		   {
		       return this._smi_Edition_Descr;
		   }
		   set
		   {
		       if( Smi_edition_descr == value )
		  return;
		 
		  _smi_Edition_Descr = value;
		  this.OnPropertyChanged("Smi_edition_descr");
		   }
		}
		public event PropertyChangedEventHandler PropertyChanged;
		protected virtual void OnPropertyChanged( string info )
		{
			if( this.PropertyChanged != null)
				this.PropertyChanged( this, new PropertyChangedEventArgs( info ) );
		}
	}
}
