#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using System.ComponentModel;
using EffixReportSystem;


namespace EffixReportSystem	
{
	public partial class EntitiesModel : OpenAccessContext, IEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntityDiagrams1.rlinq");
	
		public EntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public EntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<EF_User> EF_Users 
		{
	    	get
	    	{
	        	return this.GetAll<EF_User>();
	    	}
		}
		
		public IQueryable<EF_User_Activity> EF_User_Activities 
		{
	    	get
	    	{
	        	return this.GetAll<EF_User_Activity>();
	    	}
		}
		
		public IQueryable<EF_Tonality> EF_Tonalities 
		{
	    	get
	    	{
	        	return this.GetAll<EF_Tonality>();
	    	}
		}
		
		public IQueryable<EF_SMI_Type> EF_SMI_Types 
		{
	    	get
	    	{
	        	return this.GetAll<EF_SMI_Type>();
	    	}
		}
		
		public IQueryable<EF_SMI_priority> EF_SMI_priorities 
		{
	    	get
	    	{
	        	return this.GetAll<EF_SMI_priority>();
	    	}
		}
		
		public IQueryable<EF_SMI> EF_SMIs 
		{
	    	get
	    	{
	        	return this.GetAll<EF_SMI>();
	    	}
		}
		
		public IQueryable<EF_Publication> EF_Publications 
		{
	    	get
	    	{
	        	return this.GetAll<EF_Publication>();
	    	}
		}
		
		public IQueryable<EF_Project> EF_Projects 
		{
	    	get
	    	{
	        	return this.GetAll<EF_Project>();
	    	}
		}
		
		public IQueryable<EF_Exclusivity> EF_Exclusivities 
		{
	    	get
	    	{
	        	return this.GetAll<EF_Exclusivity>();
	    	}
		}
		
		public IQueryable<EF_Dictionary> EF_Dictionaries 
		{
	    	get
	    	{
	        	return this.GetAll<EF_Dictionary>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "azure";
			backend.ProviderName = "System.Data.SqlClient";
			return backend;
		}
	}

	public interface IEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<EF_User> EF_Users 
		{ 
			get;
		}

		IQueryable<EF_User_Activity> EF_User_Activities 
		{ 
			get;
		}

		IQueryable<EF_Tonality> EF_Tonalities 
		{ 
			get;
		}

		IQueryable<EF_SMI_Type> EF_SMI_Types 
		{ 
			get;
		}

		IQueryable<EF_SMI_priority> EF_SMI_priorities 
		{ 
			get;
		}

		IQueryable<EF_SMI> EF_SMIs 
		{ 
			get;
		}

		IQueryable<EF_Publication> EF_Publications 
		{ 
			get;
		}

		IQueryable<EF_Project> EF_Projects 
		{ 
			get;
		}

		IQueryable<EF_Exclusivity> EF_Exclusivities 
		{ 
			get;
		}

		IQueryable<EF_Dictionary> EF_Dictionaries 
		{ 
			get;
		}

	}
}
#pragma warning restore 1591

